apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
        - name: portfolio-app
          image: portfolio-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-app-service
spec:
  type: NodePort
  selector:
    app: portfolio-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31426