apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-dev
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dev
  template:
    metadata:
      labels:
        app: postgres-dev
    spec:
      containers:
        - name: postgres
          image: 258215413901.dkr.ecr.eu-north-1.amazonaws.com/postgres:15
          env:
            - name: POSTGRES_DB
              value: portfolio
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc-dev
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service-dev
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: postgres-dev
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432